# Generated by Django 3.1.3 on 2021-01-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
